# Generated by Django 3.0.4 on 2020-03-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litmus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_you',
        ),
        migrations.AddField(
            model_name='profile',
            name='signip_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
