# Generated by Django 3.0.4 on 2020-04-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litmus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
