# Generated by Django 3.0.4 on 2020-03-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litmus', '0002_auto_20200328_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='signip_confirmation',
            new_name='signup_confirmation',
        ),
    ]
