# Generated by Django 3.0.3 on 2020-04-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
