# Generated by Django 3.0.3 on 2020-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_notes_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
